//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class UserClassWrap
{
	public static void Register(LuaState L)
	{
//		L.BeginClass(typeof(UserClass), typeof(System.Object));
//		L.RegFunction("TestFunc1", TestFunc1);
//		L.RegFunction("New", _CreateUserClass);
//		L.RegFunction("__tostring", ToLua.op_ToString);
//		L.EndClass();
	}
//
//	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
//	static int _CreateUserClass(IntPtr L)
//	{
//		try
//		{
//			int count = LuaDLL.lua_gettop(L);
//
//			if (count == 0)
//			{
//				UserClass obj = new UserClass();
//				ToLua.PushObject(L, obj);
//				return 1;
//			}
//			else
//			{
//				return LuaDLL.luaL_throw(L, "invalid arguments to ctor method: UserClass.New");
//			}
//		}
//		catch (Exception e)
//		{
//			return LuaDLL.toluaL_exception(L, e);
//		}
//	}

//	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
//	static int TestFunc1(IntPtr L)
//	{
//		try
//		{
//			ToLua.CheckArgsCount(L, 4);
//			int arg0 = (int)LuaDLL.luaL_checknumber(L, 1);
//			string arg1 = ToLua.CheckString(L, 2);
//			UnityEngine.Vector3 arg2 = ToLua.ToVector3(L, 3);
//			UnityEngine.Transform arg3 = (UnityEngine.Transform)ToLua.CheckObject<UnityEngine.Transform>(L, 4);
//			UserClass.TestFunc1(arg0, arg1, arg2, arg3);
//			return 0;
//		}
//		catch (Exception e)
//		{
//			return LuaDLL.toluaL_exception(L, e);
//		}
//	}
}

